### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by panda912** [linroid/sadb#6]
Collecting sadb
  Downloading sadb-0.0.3.tar.gz
Installing collected packages: sadb
  Running setup.py install for sadb ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/ry/jqzp89x10cz_tqkd4dc82h4h0000gn/T/pip-build-TfP0zv/sadb/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/ry/jqzp89x10cz_tqkd4dc82h4h0000gn/T/pip-QeuSNK-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/sadb
    copying sadb/__init__.py -> build/lib/sadb
    running install_lib
    creating /Library/Python/2.7/site-packages/sadb
    error: could not create '/Library/Python/2.7/site-packages/sadb': Permission denied
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/ry/jqzp89x10cz_tqkd4dc82h4h0000gn/T/pip-build-TfP0zv/sadb/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/ry/jqzp89x10cz_tqkd4dc82h4h0000gn/T/pip-QeuSNK-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/ry/jqzp89x10cz_tqkd4dc82h4h0000gn/T/pip-build-TfP0zv/sadb/

**Comment by kaiziwangzi** [comment]
try this : sudo pip install sadb

**Comment by xlzd** [comment]
use `sudo pip install sadb` or `pip install sadb --user`. @panda912
