### ISSUE TITLE
同上

### ISSUE THREAD

**Issue by KBiteMan** [linroid/sadb#8]
![image](https://user-images.githubusercontent.com/24225757/34251605-a61aaa76-e67b-11e7-9d80-1883aa707e04.png)

![image](https://user-images.githubusercontent.com/24225757/34251645-c69fe568-e67b-11e7-80e9-d2ecad5af392.png)

**Comment by linroid** [comment]
已解决，可以执行以下命令更新下，谢谢支持~
```bash
pip install sadb --upgrade
```
