### ISSUE TITLE
不支持 recovery 模式下使用

### ISSUE THREAD

**Issue by drakeet** [linroid/sadb#9]
如图，`adb` 可以在 recovery 下正常使用，但 `sadb` 则会报错：
```
No device found
```
![image](https://user-images.githubusercontent.com/5214214/34325109-1ecc60b0-e8c3-11e7-837a-9872cf16dbcf.png)

感谢！

**Comment by linroid** [comment]
已解决，可以执行以下命令更新下，谢谢支持~
```bash
pip install sadb --upgrade
```
